# Generated by Django 5.1.15 on 2026-09-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '__first__'),
        ('progress', '0002_courseprogress_moduleprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='purchase_price_in_paise',
            field=models.IntegerField(default=0, help_text='Amount paid in paise at enrollment'),
        ),
    ]
