# Generated by Django 5.1.15 on 2026-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price_in_paise',
            field=models.IntegerField(blank=True, default=149900, help_text='Discounted selling price in paise', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price_in_paise',
            field=models.IntegerField(blank=True, default=199900, help_text='Original price in paise before discount (e.g. 199900 for ₹1,999)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_in_paise',
            field=models.IntegerField(default=149900, help_text='Selling price in paise (e.g. 149900 for ₹1,499)'),
        ),
    ]
